pipeline {
    agent any

    stages {
        
        stage ('checkout SCM') {

            steps {
                git 'https://github.com/Nakshatra-Software/devops-master-class.git'
            }
        }
        stage ('Compile Stage') {

            steps {
                withMaven(maven : '3.6.3') {
                    sh 'git --version'
                    sh 'java -version'
                    sh 'mvn --version'
                    
                }
            }
        }

      }
}
