pipeline {
    agent any

    stages {
        
        stage ('checkout SCM') {

            steps {
                git 'https://github.com/Nakshatra-Software/devops-master-class.git'
            }
        }
        stage ('Compile Stage') {

            steps {
                def mavenHome =  tool name: "3.6.3"
                def mavenCMD = "${mavenHome}/bin/mvn"
                sh "${mavenCMD} clean package"
                }
            }
        }
}
