pipeline {
    agent any

    stages {
        
        stage ('checkout SCM') {

            steps {
                git 'https://github.com/Nakshatra-Software/devops-master-class.git'
            }
        }
        stage ('Compile Stage') {

            steps {
                withMaven(maven : '3.6.3') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : '3.6.3') {
                    sh 'mvn test'
                }
            }
        }


        stage ('Deployment Stage') {
            steps {
                withMaven(maven : '3.6.3') {
                    sh 'mvn package'
                }
            }
        }
    }
}
